server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vms?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: qhx286118

